### PR TITLE
Mj/gu cdk migration 1

### PR DESCRIPTION
**Pull request by michaelbjacobson**
This PR introduces GuCDK to the repo, but continues to use the existing cfn.yaml file to generate the new templates. This is the initial step in the migration process.

### CODE REVIEW

**Comment by michaelbjacobson** [comment]
[support-reminders GuCDK Migration - Step 1](https://trello.com/c/MxoIm6Nw/921-support-reminders-gucdk-migration-step-1)

**Comment by michaelbjacobson** [comment]
[support-reminders GuCDK Migration - Step 1](https://trello.com/c/b2trNCad/920-support-reminders-gucdk-migration-step-1)

**Review by rupertbates — APPROVED** [review]
Looks good, it would be good to add a link in the PR description to any docs on the process you are following so that others can use it in future

**Comment by michaelbjacobson** [comment]
> Looks good, it would be good to add a link in the PR description to any docs on the process you are following so that others can use it in future

I'm writing up a separate guide for others, including external resources, based on my learnings during this migration.

**Pull request merged**
